### ISSUE TITLE
Following the installation steps leads to permission error

### ISSUE THREAD

**Issue by octavz** [snapcrafters/slack-term#7]
install with snap 
make a file config in ~/.config/slack-term/config
run:
 `couldn't find the slack-term config file: open /home/user/.config/slack-term/config: permission denied`

**Comment by mskr** [comment]
One approach for you could be to learn and apply the chmod command.

**Comment by octavz** [comment]
Sorry for bothering you, you could have just close this w/o "helping" at all.
